In [1]:
print("Olá mundo")

Olá mundo


In [ ]:
# Isto é um comentário.

In [5]:
# Declarar variáveis e operações básicas.

a=2
b=10

c=(a+b-3*a/b)
d=b**a

print("c = ",c)
print("d = ",d)

c =  11.4
d =  100


In [8]:
# Importando bibliotecas.

import numpy as np
import matplotlib.pyplot as plt

In [12]:
# Numpy:

u = np.zeros((5,5))
print(u)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
u_r = np.random.random((5,5))
print(u_r)


[[0.02777882 0.61238956 0.64011038 0.38614757 0.68978007]
 [0.82882871 0.23660675 0.09969017 0.25606966 0.43594914]
 [0.21703658 0.86562833 0.20440685 0.58554643 0.47845192]
 [0.78266807 0.11143786 0.66757611 0.58429548 0.56131942]
 [0.8768179  0.58567551 0.38398835 0.75556262 0.52948599]]


In [16]:
u_23 = u_r[2,3]
print("Em i=2 e j=3, u =", u_23)

Em i=2 e j=3, u = 0.5855464326529164


In [1]:
# Loops, condicionais

v = [0,1,2,3]
for i in v:
    if i<=2: print(i)
    else: print(0)
    

0
1
2
0


In [3]:
# Funções

def soma(a,b):
    c=a+b
    return c
s = soma(5,55)
print(s)


60
